language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install:
  - pip install coverage
  - pip install $DJANGO
script:
  - coverage run runtests.py
  - coverage report -m
env:
  - DJANGO="Django==1.4.12"
  - DJANGO="Django==1.5"
  - DJANGO="Django==1.5.7"
  - DJANGO="Django==1.6.4"
  - DJANGO="Django==1.7.11"
matrix:
  exclude:
    # Python 2.6 support has been dropped in Django 1.7
    - python: "2.6"
      env: DJANGO="Django==1.7.11"
    - python: "3.4"
      env: DJANGO="Django==1.4.12"
